Instance,Runtime (seconds),Feasible,Profit,Error
lrc103C.txt,0.94,No,-inf,"[Error running script: Command '['python3', 'main.py', '--instance_path', '/home/akkermanfr/competition_master/Instances/lrc103C.txt']' returned non-zero exit status 1.. Details: Traceback (most recent call last):
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/main.py"", line 51, in <module>
    sol = main(instance)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/main.py"", line 26, in main
    routes, numtrucks = ClusteringAndNearestNeigbor(instance_dict)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/h2_constructiveHeuristic.py"", line 351, in ClusteringAndNearestNeigbor
    clusters = Clustering(data, i)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/h2_constructiveHeuristic.py"", line 45, in Clustering
    agg_clustering = AgglomerativeClustering(n_clusters=n_clusters, affinity='precomputed', linkage='average')
TypeError: AgglomerativeClustering.__init__() got an unexpected keyword argument 'affinity'
]"
lrc303C.txt,0.92,No,-inf,"[Error running script: Command '['python3', 'main.py', '--instance_path', '/home/akkermanfr/competition_master/Instances/lrc303C.txt']' returned non-zero exit status 1.. Details: Traceback (most recent call last):
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/main.py"", line 51, in <module>
    sol = main(instance)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/main.py"", line 26, in main
    routes, numtrucks = ClusteringAndNearestNeigbor(instance_dict)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/h2_constructiveHeuristic.py"", line 351, in ClusteringAndNearestNeigbor
    clusters = Clustering(data, i)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/h2_constructiveHeuristic.py"", line 45, in Clustering
    agg_clustering = AgglomerativeClustering(n_clusters=n_clusters, affinity='precomputed', linkage='average')
TypeError: AgglomerativeClustering.__init__() got an unexpected keyword argument 'affinity'
]"
lrc203C.txt,0.92,No,-inf,"[Error running script: Command '['python3', 'main.py', '--instance_path', '/home/akkermanfr/competition_master/Instances/lrc203C.txt']' returned non-zero exit status 1.. Details: Traceback (most recent call last):
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/main.py"", line 51, in <module>
    sol = main(instance)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/main.py"", line 26, in main
    routes, numtrucks = ClusteringAndNearestNeigbor(instance_dict)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/h2_constructiveHeuristic.py"", line 351, in ClusteringAndNearestNeigbor
    clusters = Clustering(data, i)
  File ""/home/akkermanfr/repos/tlm-assignment-2-furniture-distribution-company-submissions/tlm-assignment-2-furniture-distribution-company-group-1/Group1/h2_constructiveHeuristic.py"", line 45, in Clustering
    agg_clustering = AgglomerativeClustering(n_clusters=n_clusters, affinity='precomputed', linkage='average')
TypeError: AgglomerativeClustering.__init__() got an unexpected keyword argument 'affinity'
]"
